### ISSUE TITLE
Support for @ignore and @@ignore

### ISSUE THREAD

**Issue by farreldarian** [farreldarian/prisma-generator-drizzle#12]
Add support for [@ignore](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#ignore) and [@@ignore](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#ignore-1), by filtering out any columns that has the @ignore decorator, or simply don't generate when the model has the @@ignore decorator

Raised from:
https://github.com/farreldarian/prisma-generator-drizzle/issues/1#issuecomment-1874838850

**Comment by Scalahansolo** [comment]
It seems worth being specific that if a model (table) has `@@ignore` that entire model should be ignored

**Comment by farreldarian** [comment]
> It seems worth being specific that if a model (table) has `@@ignore` that entire model should be ignored

Yeah thanks, i've just updated the description

**Comment by farreldarian** [comment]
@Scalahansolo, I just checked the @ignore and @@ignore support, it looks like the `@prisma/generator-helper` already exclude any ignored fields or models. Therefore I just added a test to make sure the behavior without adding any feature. Let me know if I'm getting this correctly
