### ISSUE TITLE
Option to suppress generator output?

### ISSUE THREAD

**Issue by Scalahansolo** [farreldarian/prisma-generator-drizzle#15]
First off, Im so thankful for this lib. Not yet using it in production, but it's allowing me to properly test Drizzle with my prod schemas and will make migrating off Prisma so much easier. Onto my idea...

My Prisma schema is pretty massive... I would love to have an option in the generator to suppress the output of the generator. I know where the files are going and it just ends up making a lot of noise and I run `prisma generate`

**Comment by farreldarian** [comment]
Yeah this totally make sense. I think I'm gonna set this behavior as the default and add an optional `log = 'verbose'` configuration.
