### ISSUE TITLE
Check tsconfig and add .ts to imports

### ISSUE THREAD

**Issue by hilja** [farreldarian/prisma-generator-drizzle#18]
![Screenshot 2024-01-12 at 17 16 01](https://uploads.linear.app/96fb5f2a-1188-41c2-bf5a-84e8b0f0dc0d/1b8386b1-046d-4631-a8f9-d4360b476059/bf7900b2-d848-4b2e-9c10-084b74638459?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk2ZmI1ZjJhLTExODgtNDFjMi1iZjVhLTg0ZThiMGYwZGMwZC8xYjgzODZiMS0wNDZkLTQ2MzEtYThmOS1kNDM2MGI0NzYwNTkvYmY3OTAwYjItZDg0OC00YjJlLTljMTAtMDg0Yjc0NjM4NDU5IiwiaWF0IjoxNzA1NjY0Nzk1LCJleHAiOjMzMjc2MjI0Nzk1fQ.77_Nga1xvWaClCLBIv-nHqB6DWWB2hKebDO3k19j8mw)

Not a big problem, but if you’ve got something like this in tsonfig you need to import with `.ts` extension. Could also be a setting.

```
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "allowImportingTsExtensions": true,
  }
}
```

**Comment by hilja** [comment]
Ah, this won't work https://github.com/drizzle-team/drizzle-orm/issues/849 I ran the generator yesterday evening and didn't try to migrate until this morning and noticed it can't find the tables.

**Comment by hilja** [comment]
This is the way:

```
"scripts": {
  "generate": "NODE_OPTIONS='--import tsx' drizzle-kit generate:pg"
}
```

A bit off-topic but, is the following supposed to work?

```ts
export default defineConfig({
  schema: './drizzle/schema/schema.ts',
})
```

It can't find any tables from the `schema.ts`, but glob works fine :) 

```ts
export default defineConfig({
  schema: './drizzle/schema/*',
})
```

**Comment by farreldarian** [comment]
@hilja do you mind making a repository where I can reproduce the issue? 

So far I'm importing the generated models in a next.js project (using the tsconfig created from `create-next-app`) and a [simple ts project](https://github.com/farreldarian/prisma-generator-drizzle/blob/0422a3a25f9f55965a6e5b5c674497396bfc7e21/packages/usage/src/index.ts#L10) works fine

**Comment by daniel-nagy** [comment]
I have the same issue. To make things easy I believe this library could just always add the `.js` extension to the import path. I believe that would work in all cases but I could be wrong.

**Comment by daniel-nagy** [comment]
I just opened a PR to add the js extension. @hilja as a temporary workaround you can use my fork by installing it from a git URL.

```
yarn add daniel-nagy/prisma-generator-drizzle#js-ext-pkg
```

**Comment by farreldarian** [comment]
@daniel-nagy @hilja I just patched the import logic to determine based on the project's moduleResolution, let me know if it's not working

**Comment by farreldarian** [comment]
> @daniel-nagy @hilja I just [patched the import logic](https://github.com/farreldarian/prisma-generator-drizzle/pull/29) to determine based on the project's moduleResolution, let me know if it's not working

It breaks on my repo 😅

I couldn't find any better approach, so I just provide [the config to override](https://github.com/farreldarian/prisma-generator-drizzle/pull/30)
