### ISSUE TITLE
Provide default export for all schema

### ISSUE THREAD

**Issue by farreldarian** [farreldarian/prisma-generator-drizzle#19]
Using `schema.ts` for drizzle-kit doesn't expose any schema.

```ts
export default defineConfig({
  schema: './drizzle/schema/schema.ts',
})
```

It can't find any tables from the `schema.ts`, but glob works fine

```ts
export default defineConfig({
  schema: './drizzle/schema/*',
})
```

_Originally posted by @hilja in https://github.com/farreldarian/prisma-generator-drizzle/issues/18#issuecomment-1890462189_

**Comment by farreldarian** [comment]
After some thinking, it might be better to just recommend the use of glob pattern instead of introducing another `index.ts` that re-exports all schema since it'll make IDE to give duplicate recommendations when importing a table. Also barrel file is normally better to be avoided because of (IDE) performance issue

**Comment by hilja** [comment]
That's great, mentioning it in the docs basically solves the issue. Thank for all the work!
