### ISSUE TITLE
Cockroachdb provider support (same as postgres)

### ISSUE THREAD

**Issue by Scalahansolo** [farreldarian/prisma-generator-drizzle#9]
I saw that in your V1 notes, you didn't call out CockroachDB support. For the sake of this lib, I think it would just be simple enough to generate CockroachDB models in the same way you do Postgres. CockroachDB is designed and meant to be Postgres compatible.

```
datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}
```

**Comment by farreldarian** [comment]
I'm not familiar with cockroachdb, does it uses the [pg adapter](https://orm.drizzle.team/docs/get-started-postgresql) on Drizzle?

**Comment by Scalahansolo** [comment]
It does. I use postgres js all the time when talking with Cockroach DB. So it should work fine to us https://orm.drizzle.team/docs/get-started-postgresql#postgresjs to talk with cockroach.

**Comment by farreldarian** [comment]
Relesed 🚀 https://github.com/farreldarian/prisma-generator-drizzle/releases/tag/v0.5.3

Many thanks @Scalahansolo
